# Base image
FROM node:16

# Set working directory in the container
WORKDIR /app/

# Copy package.json and package-lock.json
COPY package*.json ./

# # Configure npm
# RUN npm config set timeout 600000 && \
#     npm config set retry 5 && \
#     npm config set strict-ssl false

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port (update with your app's port if needed)
EXPOSE 5000

# Start the application
CMD ["node", "customers.js"]  
